dist: trusty
sudo: required
osx_image: xcode8.3
language: java

os:
  - linux
  - osx

env:
  - BAZEL_VERSION=0.9.0
  - BAZEL_VERSION=0.11.1

before_install:
  - echo $TRAVIS_OS_NAME;
  - unset CC
  - unset CXX
  - scripts/install_bazel.sh

script:
  - bazel test --crosstool_top=//tools/cpp:default-toolchain //src/...

notifications:
  email: false
  slack: false
