dist: trusty

osx_image: xcode8.3
language: java

os:
  - linux
  - osx

env:
  - BAZEL_VERSION=0.12.0
  - BAZEL_VERSION=0.13.1
  - BAZEL_VERSION=0.14.1
  - BAZEL_VERSION=0.15.2
  - BAZEL_VERSION=0.16.1
  - BAZEL_VERSION=0.17.2
  - BAZEL_VERSION=0.18.1
  - BAZEL_VERSION=0.19.2

matrix:
  fast_finish: true

before_install:
  - echo $TRAVIS_OS_NAME;
  - unset CC
  - unset CXX
  - scripts/install_bazel.sh

script:
  - bazel test --crosstool_top=//tools/cpp:default-toolchain //src/...

notifications:
  email: false
  slack: false
